### PR TITLE
Add testIds to profile form

### PR DESCRIPTION
**Pull request by wdsrocha**
#### What problem is this solving?

Add testIds to improve e2e tests development. See [this](https://github.com/vtex-apps/checkout-io-tests/pull/4#discussion_r429239714).

#### How should this be manually tested?

Clone [this branch](https://github.com/vtex-apps/checkout-io-tests/pull/4) locally and run yarn e2e. Don't forget to login on VTEX (toolbelt). It should pass every profile test.

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
_ | New feature 
_ | Breaking change 
✔️ | Technical improvements

### CODE REVIEW

**Comment by wdsrocha** [comment]
This would be a `patch` to release, right?

**Comment by lucasecdb** [comment]
> This would be a `patch` to release, right?

yep :-)

**Review by marcoskwkm — APPROVED** [review]
LGTM. I'm just not sure about adding `-wrapper` to every id.

**Comment by lucasecdb** [comment]
> I'm just not sure about adding `-wrapper` to every id.

@marcoskwkm the "rationale" was that the id isn't on the actual element of what we want (e.g. the phone field id isn't on the phone field input itself and so on), but we could change it to remove the suffix

**Comment by marcoskwkm** [comment]
> @marcoskwkm the "rationale" was that the id isn't on the actual element of what we want (e.g. the phone field id isn't on the phone field input itself and so on), but we could change it to remove the suffix

Yeah, that's what I thought. I was just thinking that if you're adding the id to target the inner element (like checking if it exists) and not the wrapper itself, then I'd remove the `wrapper` suffix, but this is perfectly fine.

**Review by lucasecdb — APPROVED** [review]

**Pull request merged**
