### PR TITLE
CHUI-67: Add logout button to profile summary

### PR DESCRIPTION
**Pull request by lucasecdb**
#### What problem is this solving?

Adds the button so the user can logout directly on Checkout.

#### How should this be manually tested?

[Workspace](https://sndpurchase--checkoutio.myvtex.com/).

Test plan:

1. Unauthenticated, identified:
   1. Enter in the above workspace, add an item to your cart.
   2. Proceed to Checkout, and enter a second purchase email (you can use `lucas.brito@vtex.com.br` if you want).
   3. In Checkout, click the "not you? logout" button and you should be redirected to the identification page.
2. Authenticated:
   1. Enter in the above workspace again, and log in into your account.
   2. Add an item to your cart.
   3. Proceed to Checkout.
   4. In Checkout, click in the "not you? logout" button, you should be redirected to the identification page and should not be logged in your account.

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [x] Linked this PR to a Jira story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
✔️ | New feature 
_ | Breaking change 
_ | Technical improvements

### CODE REVIEW

**Comment by wdsrocha** [comment]
I found a way to be logged with an email and have a another email on profile step. Is that ok?

Steps to reproduce:

1. Login on home
2. Add anything on cart and go to checkout
3. Click in "edit profile step"
4. Click in "Preencher informações para" (to go back to identification)
5. Continue with a different email

Now, if you go back to home, you'll see that the first email is still logged. I think it kind of makes sense, but I'm reporting here just to be sure.

**Comment by lucasecdb** [comment]
> I found a way to be logged with an email and have a another email on profile step. Is that ok?

we were discussing with the identity team exactly about this issue earlier this week, to identify in Checkout with one email but authenticate with another and it sort of makes sense. In the same way we won't be able to "forbid" the user to authenticate with other emails during the Checkout after they identified themselves with another email, we can't forbid this scenario as well :-/

**Comment by wdsrocha** [comment]
Also, as this is a new feature, why there are no tests? (not to sound arrogant or anything, I genuinely would like to know lol)
And could you add a `data-testid` attribute, so we can make e2e tests on this later on?

**Comment by lucasecdb** [comment]
> Also, as this is a new feature, why there are no tests? (not to sound arrogant or anything, I genuinely would like to know lol)

it's because this functionality affects multiple apps. I don't think unit testing here would benefit us much because we would be mocking a lot of stuff anyway :-/

> And could you add a `data-testid` attribute, so we can make e2e tests on this later on?

sure!

**Comment by wdsrocha** [comment]
> it's because this functionality affects multiple apps. I don't think unit testing here would benefit us much because we would be mocking a lot of stuff anyway :-/

Fair enough, ty

**Review by wdsrocha — APPROVED** [review]

**Review by marcoskwkm — APPROVED** [review]

**Review by augustocb — COMMENTED** [review]
image

Fields should not be shown when I'm not authenticated.

1. Type any email (1st purchase)
2. Click to edit
3. Type `lucas.brito@vtex.com.br`

**Comment by lucasecdb** [comment]
> Fields should not be shown when I'm not authenticated.
> 
>   1. Type any email (1st purchase)
> 
>   2. Click to edit
> 
>   3. Type `lucas.brito@vtex.com.br`

@augustocb I fixed this in another workspace (because it's related to another clubhouse story, the one with "steps validation"), could you disconsider this? 😅 [this is the workspace](https://steps--checkoutio.myvtex.com/) if you want to check it out, but it won't have the other improvements for the second purchase like this one.

**Review by augustocb — APPROVED** [review]
LATM

**Pull request merged**
